name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Folder setup
            sudo rm -rf ~/brew-be
            mkdir -p ~/brew-be
            cd ~/brew-be

            # 2. Clone Public Repo
            git clone https://github.com/${{ github.repository }}.git .

            # 3. Install Tools
            npm install
            sudo npm install -g ts-node typescript pm2

            # 4. Start PM2 from src folder
            pm2 delete brew-be-api || true
            
            # YAHAN DHYAN DO: Path src/index.ts use kiya hai
            pm2 start src/index.ts --name "brew-be-api" --interpreter ts-node

            # 5. Save settings
            pm2 save