name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Purana folder saaf karke fresh start
            rm -rf ~/brew-be
            mkdir -p ~/brew-be
            cd ~/brew-be

            # 2. Code clone karna (Dot '.' ka matlab isi folder mein files aayengi)
            git clone https://github.com/${{ github.repository }}.git .

            # 3. Dependencies install karna
            npm install

            # 4. TypeScript compiler aur ts-node check/install
            sudo npm install -g ts-node typescript

            # 5. Purana process delete karke naya start karna
            # --interpreter ts-node isliye kyunki tumhari file index.ts hai
            pm2 delete brew-be-api || true
            pm2 start index.ts --name "brew-be-api" --interpreter ts-node